[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_BASE_URL,NEXTAUTH_URL,DATABASE_URL"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://st-helens-report-card.netlify.app/*"
  to = "https://result.sthelenskurseong.in/:splat"
  status = 301
  force = true